### ISSUE TITLE
Remove "List are not allowed" error raised for example images for non-ILB jobs

### ISSUE THREAD

**Issue by jjanii** [hCaptcha/hmt-basemodels#27]
https://github.com/hCaptcha/hmt-basemodels/blob/master/basemodels/manifest.py#L106

mentioned here:
https://github.com/IntuitionMachines/dashboard-v2/issues/502#issuecomment-590654522

**Comment by gaieges** [comment]
This depends on what the frontend can support, at the moment.. @brdlyptrs do you know which should be enabled/disabled?

**Comment by brdlyptrs** [comment]
Supported:
- Area Select Polygon
- Area Select Bounding Box
- Landmark
- Binary Grid

Not Supported:
- Text Input
- Multi-Choice / Categorization
