### ISSUE TITLE
Add image upload pipeline

### ISSUE THREAD

**Issue by rodriguez-facundo** [hCaptcha/hmt-basemodels#67]

**Comment by TaSeeMba** [comment]
can you please remove me from this Org and repo

**Comment by unmeshk** [comment]
@TaSeeMba You are already removed from this org and repo. What seems to be the problem?

**Comment by TaSeeMba** [comment]
I keep getting notifications

**Comment by rustyro** [comment]
> I keep getting notifications

@TaSeeMba You're watching this repo. To stop recieving notifications you'll have to unwatch, using the `unwatch` button on the top right corner
